server:
  port: 8080
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://121.40.166.14:3306/microServer?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: aliyun7mysql@7c
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 121.40.166.14
      port: 6379
      password: aliyun123
      database: 1


